# Generated by Django 4.2.1 on 2023-06-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_address_email_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='address',
        ),
    ]
